image: golang:latest
pipelines:
  default:
    - parallel:
      - step:
          name: Linting
          services:
              - docker
          script:
              # Prepare the environment
              - export PATH=$HOME/go/bin:$PATH GOPATH=~/go SRCDIR=$HOME/go/src/bitbucket.org/atlassian/vpcflow-grapherd
              - mkdir -p $HOME/go/bin $HOME/go/src/bitbucket.org/atlassian && ln -s $BITBUCKET_CLONE_DIR $SRCDIR && cd $SRCDIR
              - apt-get update && apt-get install -y apt-transport-https ca-certificates make curl gcc git
              - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin latest
              - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

              # Get dependencies
              - make dep

              # Lint
              - make lint

      - step:
          name: Tests
          services:
              - docker
          script:
              # Prepare the environment
              - export PATH=$HOME/go/bin:$PATH GOPATH=~/go SRCDIR=$HOME/go/src/bitbucket.org/atlassian/vpcflow-grapherd
              - mkdir -p $HOME/go/bin $HOME/go/src/bitbucket.org/atlassian && ln -s $BITBUCKET_CLONE_DIR $SRCDIR && cd $SRCDIR
              - apt-get update && apt-get install -y apt-transport-https ca-certificates make curl gcc git
              - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              - go get github.com/axw/gocov/...
              - go get github.com/AlekSi/gocov-xml

              # Get dependencies
              - make dep

              # Run the tests
              - make test
          artifacts:
              - .coverage/unit.cover.out

      - step:
          name: Integration
          services:
              - docker
          script:
              # Prepare the environment
              - export PATH=$HOME/go/bin:$PATH GOPATH=~/go SRCDIR=$HOME/go/src/bitbucket.org/atlassian/vpcflow-grapherd
              - mkdir -p $HOME/go/bin $HOME/go/src/bitbucket.org/atlassian && ln -s $BITBUCKET_CLONE_DIR $SRCDIR && cd $SRCDIR
              - apt-get update && apt-get install -y apt-transport-https ca-certificates make curl gcc git
              - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              - go get github.com/axw/gocov/...
              - go get github.com/AlekSi/gocov-xml

              # Get dependencies
              - make dep

              # Run the integration tests
              - make integration
          artifacts:
              - .coverage/integration.cover.out

    - step:
        name: Coverage
        services:
            - docker
        script:
            # Prepare the environment
            - export PATH=$HOME/go/bin:$PATH GOPATH=~/go SRCDIR=$HOME/go/src/bitbucket.org/atlassian/vpcflow-grapherd
            - mkdir -p $HOME/go/bin $HOME/go/src/bitbucket.org/atlassian && ln -s $BITBUCKET_CLONE_DIR $SRCDIR && cd $SRCDIR
            - apt-get update && apt-get install -y apt-transport-https ca-certificates make curl gcc git bc jq
            - go get github.com/axw/gocov/...
            - go get github.com/AlekSi/gocov-xml
            - go get github.com/wadey/gocovmerge

            # Create coverage report
            - make coverage
