# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "v3.3.3"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.55"

[[constraint]]
  name = "github.com/google/uuid"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/asecurityteam/logevent"
  version = "^1.0.2"

[[constraint]]
  name = "github.com/rs/xstats"
  branch = "master"

[[constraint]]
  name = "github.com/asecurityteam/go-vpcflow"
  branch = "master"

[[constraint]]
  name = "github.com/asecurityteam/transport"
  version = "^1.1.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/asecurityteam/runhttp"

[[constraint]]
  branch = "master"
  name = "github.com/asecurityteam/settings"
