// Automatically generated by MockGen. DO NOT EDIT!
// Source: ./pkg/types/grapher.go

package v1

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	io "io"
)

// Mock of Grapher interface
type MockGrapher struct {
	ctrl     *gomock.Controller
	recorder *_MockGrapherRecorder
}

// Recorder for MockGrapher (not exported)
type _MockGrapherRecorder struct {
	mock *MockGrapher
}

func NewMockGrapher(ctrl *gomock.Controller) *MockGrapher {
	mock := &MockGrapher{ctrl: ctrl}
	mock.recorder = &_MockGrapherRecorder{mock}
	return mock
}

func (_m *MockGrapher) EXPECT() *_MockGrapherRecorder {
	return _m.recorder
}

func (_m *MockGrapher) Graph(_param0 context.Context, _param1 string, _param2 io.ReadCloser) error {
	ret := _m.ctrl.Call(_m, "Graph", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockGrapherRecorder) Graph(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Graph", arg0, arg1, arg2)
}
